import React , {useState} from 'react'

export default function DisplayRATE() {
//     const[rate , setRate] = useState([]);

//   const Getrat = () => {
//     axios.get("http://localhost:3030/rating").then((result)=>{
//       const myRate = result.rate;
//       setRate(myRate)
//     }).catch((err)=>{
//       console.log(err)
//     })
//   }
  

//   useEffect(() => {
//     Getrat();
//   }, []);
  return (
    <>
    <div>DisplayRATE</div>
    {/* <h5 className="card-title">Rating : - {rate.rate}</h5>
    <h5 className="card-title">Feedback : - {rate.feedback}</h5> */}
    </>
  )
}
